// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input /home/drFaustroll/playground/keyboard/qmk-alin/myfont-36.png --output /home/drFaustroll/playground/keyboard/qmk-alin/myfonts --no-ascii False --unicode-glyphs ⏮≉⋜ψΩ↹⎗⎇╯μ╭Α∮τℇ⊅⊆▲εσ⊂ç┼→⇠←∑∫Ç⨋χ⌕↓⎋ț∞⊼ωℂ≠Î🕩ℏ🖵☼↟ăÅ┌⇧ρ↡┘∆∂°⌦│ℒ─┬∏∈θî╮∇ℤ⊻⋅⌫ϕș∨↞ϰ≅├ϑ♽⊇♲☀⎘â🕪δ┴ℝ🖰π⋝Ă↠ξ∘⏾Ξ┐❖Â╰η⇑Țβ⇡⊃⇣∪γ┤⚛λ⎈≡⌧↑φΛℋ▼∩ν±⏎Γ∉∝×∧⇢≈α≢∡Ș∓🖶🕨└⇓⏽⊗⌇⏯⏭ζ␥⇪⏹⊄ --format mono4 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_myfont_36_length;
extern const uint8_t  font_myfont_36[35175];
