name: draw for mlego
on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  draw-keymaps:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - mlego/m65/rev1
          - mlego/m65/rev2
          - mlego/m65/rev3
          - mlego/m65/rev4
          - mlego/m65/rev5
          - mlego/m65/rev6
          - mlego/m65/rev7
          - mlego/m66/rev1
          - mlego/m66/rev2
          - mlego/m66/rev3
          - mlego/m66/rev4
        keymap:
          - default
          - uk
        include:
          - keyboard: mlego/m65/rev7
            keymap: default_61
          - keyboard: mlego/m60/rev1
            keymap: default
          - keyboard: mlego/m60/rev1
            keymap: default_adv
          - keyboard: mlego/m60/rev2
            keymap: default
          - keyboard: mlego/m60/rev2
            keymap: default_adv
          - keyboard: mlego/m48/rev1
            keymap: default
          - keyboard: mlego/m48/rev1
            keymap: default_adv
          - keyboard: mlego/m60_split/rev1
            keymap: default
          - keyboard: mlego/m60_split/rev2
            keymap: default
          - keyboard: mlego/m20/rev1
            keymap: default
          - keyboard: mlego/m20/rev1
            keymap: default_adv
          - keyboard: mlego/m20/rev2
            keymap: default_adv_knob
          - keyboard: mlego/m8/rev1
            keymap: default
          - keyboard: tipro/rev3
            keymap: default_120
          - keyboard: tipro/rev2
            keymap: default_96
          - keyboard: tipro/rev1
            keymap: default
          - keyboard: tipro/rev1
            keymap: default_ansiortho
          - keyboard: tipro/rev1
            keymap: default_orthoansi
          - keyboard: tipro32
            keymap: default
          - keyboard: mlego/m78/rev1
            keymap: default
          - keyboard: mlego/m78/rev2
            keymap: default
          - keyboard: mlego/m78/rev1
            keymap: uk
          - keyboard: mlego/m78/rev2
            keymap: uk

    steps:
    - name: checkout qmk
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: false

    - name: draw
      id: draw
      run: |
        git config --global --add safe.directory '*'
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install fontTools
        set -x
        #if [ -d keyboards/${{ matrix.keyboard}}/keymaps/${{ matrix.keymap }} ]; then
          qmk info -lm -kb ${{ matrix.keyboard}} -km ${{ matrix.keymap }}

          TARGET="$(echo '${{ matrix.keyboard }}' | sed 's#/#_#g')_${{matrix.keymap}}"
          echo "artifact-name=${TARGET}" >> $GITHUB_OUTPUT
          echo "artifact-name: ${{ steps.draw.outputs.artifact-name }}"
        #fi

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "${{ steps.draw.outputs.artifact-name }}"
        path: |
          *.svg
      continue-on-error: true
